### ISSUE TITLE
naprawić wyciek pamięci

### ISSUE THREAD

**Issue by jmalinwsk** [purranya/purranya_app#1]
- problem ze scenami
- przy zmienianiu sceny nie jest zwalniana pamięć po poprzedniej scenie

**Comment by jmalinwsk** [comment]
wszelkie działania związane z naprawą tego rozwiązywać na branchu "zmianaScen" 
https://github.com/purranya/purranya_app/tree/zmianaScen

**Comment by malinowskikam** [comment]
można zrobić metodę, która jak chcesz odświerzyć scenę to ręcznie wywoła destruktor i zrobi od nowa

**Comment by jmalinwsk** [comment]
fixed
